kind: ConfigMap
apiVersion: v1
metadata:
  name: api-store-config
  labels:
    app: api-store
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgres-user
  POSTGRES_PASSWORD: secret
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: api-store-volume
  labels:
    type: local
    app: api-store
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: api-store-claim
  labels:
    app: api-store
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-store
spec:
  selector:
    matchLabels:
      app: api-store
  template:
    metadata:
      labels:
        app: api-store
    spec:
      containers:
        - name: api-store
          image: postgres:12.3
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: api-store-config
          volumeMounts:
            - mountPath: /data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: api-store-claim
---
kind: Service
apiVersion: v1
metadata:
  name: api-store
  labels:
    app: api-store
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: api-store
