---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sg-public-api
  labels:
    app: sg-public-api
spec:
  selector:
    matchLabels:
      app: sg-public-api
  template:
    metadata:
      labels:
        app: sg-public-api
    spec:
      containers:
        - name: sg-public-api
          image: sg/public-api-image
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sg-public-api-svc
spec:
  type: NodePort
  selector:
    app: sg-public-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000