---
apiVersion: v1
kind: Service
metadata:
  name:  web-frontend
  annotations:
    # Note: if both `www.grouphouse.io, grouphouse.io` is included there's a DNS record naming collision
    external-dns.alpha.kubernetes.io/hostname: www.grouphouse.io
spec:
  type: LoadBalancer
  selector:
      app: web-frontend
  ports:
    - port: 80
      name: http
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
spec:
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
        - name: web-frontend
          image: web-frontend-image
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: http