---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
spec:
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
        - name: web-frontend
          image: sg/web-frontend-image
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: default
  labels:
    app: web-frontend
spec:
  type: LoadBalancer
  selector:
    app: web-frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80