---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v0.7.6
          # TODO: Change to using more robust solution than making a local secret:
          # Command: `kubectl create secret generic test-secret --from-literal=AWS_ACCESS_KEY_ID='< access key id >' --from-literal=AWS_SECRET_ACCESS_KEY='< access key >' --from-literal=AWS_HOSTED_ZONE_ID='< your target hosted zone id >'`
          envFrom:
            - secretRef:
                name: test-secret
          args:
            - --source=service
            - --source=ingress
            - --domain-filter=grouphouse.io # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
            - --provider=aws
            - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
            - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
            - --registry=txt
            - --txt-owner-id=AWS_HOSTED_ZONE_ID # your target hosted zone id
            - --txt-prefix=txt. #https://github.com/kubernetes-sigs/external-dns/blob/master/docs/faq.md#im-using-an-elb-with-txt-registry-but-the-cname-record-clashes-with-the-txt-record-how-to-avoid-this
            # - --log-level=debug