---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc
  labels:
    app: grpc
spec:
  selector:
    matchLabels:
      app: grpc
  template:
    metadata:
      labels:
        app: grpc
    spec:
      containers:
        - name: grpc
          image: docker.io/selleman/web-microservice-shell_grpc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: grpc
  labels:
    app: grpc
spec:
  type: LoadBalancer
  ports:
    - port: 8001
  selector:
    app: grpc
