---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sg-grpc
  labels:
    app: sg-grpc
spec:
  selector:
    matchLabels:
      app: sg-grpc
  template:
    metadata:
      labels:
        app: sg-grpc
    spec:
      containers:
        - name: sg-grpc
          image: sg/grpc-image
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: sg-grpc
  labels:
    app: sg-grpc
spec:
  type: LoadBalancer
  ports:
    - port: 8001
  selector:
    app: sg-grpc
