---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api
  labels:
    app: public-api
spec:
  selector:
    matchLabels:
      app: public-api
  template:
    metadata:
      labels:
        app: public-api
    spec:
      containers:
        - name: public-api
          image: docker.io/selleman/web-microservice-shell_public-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.publicAPIPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: public-api
  labels:
    app: public-api
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.publicAPIPort }}
  selector:
    app: public-api
