# External DNS
domainFilter: grouphouse.io
devMode: true

# Web Frontend
domain: staging.grouphouse.io

# Public API
publicAPIPort: 8000
allowedOrigin: http://staging.grouphouse.io

# GRPC
grpcName: grpc
grpcPort: 8001
grpcAddress: :8001

# API Store
psqlMaxConns: 40
psqlDriver: postgres
psqlPort: 5432
psqlUser: postgres-user
psqlPassword: secret # TODO: move to secrets
psqlName: postgresdb
psqlMigraterTableName: public-api
psqlMigrationPath: ./migrations
