---
apiVersion: v1
kind: Service
metadata:
  name:  web-frontend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.domain }}
spec:
  type: LoadBalancer
  selector:
      app: web-frontend
  ports:
    - port: 80
      name: http
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
        - name: web-frontend
          # Change image name so it can be pulled from dockerHub more easily
          # Could also add a different directory root for dev vs prod using an environment variable
          # directory ./ vs ./grouphouse.io (or web-microservice-shell for now)
          # i.e. fictional.registry.example/imagename, `.` for dev, `dockerhub/...` for prod
          image: docker.io/selleman/web-microservice-shell_web-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          # readinessProbe:
          #  httpGet:
          #    path: /
          #    port: 80